# Generated by Django 6.0.7 on 2026-08-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
