# Generated by Django 6.0.7 on 2026-08-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_cart_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="session_key",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
